var templates = {
    calculator: [
        '<div class="calculator-wrap">',
            '<div class="input-row">',
                '<input disabled="disabled">',
            '</div>',
            '<div class="row-btns">',
                '<button class="clear-current-field-btn">ce</button>',
                '<button class="clear-btn">c</button>',
                '<button class="dell-btn">del</button>',
                '<button class="action-btn">/</button>',
            '</div>',
            '<div class="row-btns">',
                '<button class="number">7</button>',
                '<button class="number">8</button>',
                '<button class="number">9</button>',
                '<button class="action-btn">*</button>',
            '</div>',
            '<div class="row-btns">',
                '<button class="number">4</button>',
                '<button class="number">5</button>',
                '<button class="number">6</button>',
                '<button class="action-btn">-</button>',
            '</div>',
            '<div class="row-btns">',
                '<button class="number">1</button>',
                '<button class="number">2</button>',
                '<button class="number">3</button>',
                '<button class="action-btn">+</button>',
            '</div>',
            '<div class="row-btns">',
                '<button class="plus-minus-btn">+-</button>',
                '<button class="number">0</button>',
                '<button class="dot-btn">.</button>',
                '<button class="calculate-btn">=</button>',
            '</div>',
        '</div> '
    ].join('')
};